#ifndef _LANGUAGE_JP_H_
#define _LANGUAGE_JP_H_

    #define JP_LANGUAGE             "日本語"
    #define JP_HEAT                 "あたため"
    #define JP_MOVE                 "移動"
    #define JP_HOME                 "ゼロにする"
    #define JP_PRINT                "プリント"
    #define JP_EXTRUDE              "押出"
    #define JP_FAN                  "ファン"
    #define JP_SETTINGS             "設定"
    #define JP_LEVELING             "自動調整"
    #define JP_INC                  "増え"
    #define JP_DEC                  "減る"
    #define JP_NOZZLE               "ノズル"
    #define JP_BED                  "ベッド"
    #define JP_STOP                 "停止"
    #define JP_BACK                 "戻る"
    #define JP_PAGE_UP              "前ページ"
    #define JP_PAGE_DOWN            "次ページ"
    #define JP_PAUSE                "一時停止"
    #define JP_RESUME               "続ける"
    #define JP_LOAD                 "増え"
    #define JP_UNLOAD               "減る"
    #define JP_SLOW_SPEED           "ゆっくり"
    #define JP_NORMAL_SPEED         "正常速度"
    #define JP_FAST_SPEED           "早め"
    #define JP_FAN_FULL_SPEED       "全速"
    #define JP_FAN_HALF_SPEED       "50%速さ"
    #define JP_POWER_OFF            "Power Off"
    #define JP_TOUCHSCREEN_ADJUST   "校正する"
    #define JP_SCREEN_INFO          "ついて"
    #define JP_DISCONNECT           "データ接続"
    #define JP_BAUDRATE_115200      "115200"
    #define JP_BAUDRATE_250000      "250000"
    #define JP_PERCENTAGE           "Percentage"
    #define JP_BABYSTEP             "BabyStep"
    #define JP_PERCENTAGE_SPEED     "スビード%"
    #define JP_PERCENTAGE_FLOW      "押出%"
    #define JP_VALUE_ZERO           "Zero"
    #define JP_1_DEGREE             "1℃"
    #define JP_5_DEGREE             "5℃"
    #define JP_10_DEGREE            "10℃"
    #define JP_X_INC                "X+"
    #define JP_Y_INC                "Y+"
    #define JP_Z_INC                "Z+"
    #define JP_X_DEC                "X-"
    #define JP_Y_DEC                "Y-"
    #define JP_Z_DEC                "Z-"
    #define JP_X_HOME               "X"
    #define JP_Y_HOME               "Y"
    #define JP_Z_HOME               "Z"
    #define JP_001_MM               "0.01mm"
    #define JP_01_MM                "0.1mm"
    #define JP_1_MM                 "1mm"
    #define JP_5_MM                 "5mm"
    #define JP_10_MM                "10mm"
    #define JP_1_PERCENT            "1%"
    #define JP_5_PERCENT            "5%"
    #define JP_10_PERCENT           "10%"

    #define JP_READY                "準備中"
    #define JP_PRINTING             "プリント中"
    #define JP_BUSY                 "ビジー状態、しばらくお待ちください..."
    #define JP_UNCONNECTED          "プリンターに連続していない!"
    #define JP_DISCONNECT_INFO      "SDカード　PC両用"
    #define JP_LOADING              "ロッド中..."
    #define JP_READ_SD_ERROR        "ＳＤカードの読み取りがエラー発生しました!"    
    #define JP_POWER_FAILED         "Continue printing?"
    #define JP_CONTINUE             "継続"
    #define JP_CANNEL               "キャンセル"
    #define JP_ADJUST_TITLE         "タッチスクリーン較正"
    #define JP_ADJUST_INFO          "赤星をタッチ"
    #define JP_ADJUST_OK            "校正が成功しました"
    #define JP_ADJUST_FAILED        "校正が失敗しました、も一度お試して下さい"
    #define JP_WARNING              "Warning"
    #define JP_STOP_PRINT           "プリントを中止しますか?"
    #define JP_CONFIRM              "確定"

    #define JP_ONBOARD              "機内で"  // Google translator. I don't know the language. Please correct
    #define JP_TFT                  "TFT"


#endif
